title: "Delayed Welcome Messages for Discord"
author: "ACuteWoof"
description: 'Made with <b style="color: #f45;">&lt;3</b>'
permalink: /:title/
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_excerpts: true # show article excerpts on the home page
show_frame: true # adds a gray frame to the site
show_sidebar: false # show a sidebar instead of the usual header
minimal: false # use a dark header

# Menu

navigation: # accepts {file, title, url, icon, sidebaricon}
  - { file: "index.html" }
  - { file: "index.md" }

external: # shows a footer with social links - for available icons see fontawesome.com/icons
  - {
      title: Github,
      icon: github,
      url: "https://github.com/ACuteWoof/delayed-welcome-messages",
    }

comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
  - jekyll-feed
